# Schedule'parameter
batching_timeout = 1 
instance_num =1

[jpg_decoder]
backend = "SyncTensor[ Sequential[DecodeTensor,ResizeTensor,cvtColorTensor] ]" 
resize_h = 232
resize_w = 232 
color = "rgb"
next = "cpu_decoder"
instance_num =3

[cpu_decoder]
backend = "Sequential[DecodeMat,ResizeMat,cvtColorMat,Mat2Tensor,SyncTensor]" 
filter = "or" 
resize_h = 232 
resize_w = 232 
color = "rgb"
instance_num =4


