# Schedule'parameter
batching_timeout = 6 #默认的凑batch的超时时间
instance_num = 1 
precision = "fp16" 
[jpg_decoder]
filter="run"
backend = "SyncTensor[ Sequential[DecodeMat,Mat2Tensor,ResizeTensorV1,cvtColorTensor]  ]" # 需要处理背景线程cuda流同步问题可用SyncTensor， 否则可用Sequential；SyncTensor确保初始化和前向在同一个线程时，能准确处理多个backend的同步时机
resize_h = 224 
resize_w = 224 

color = "rgb"
# next = "cpu_decoder"
# device = "cpu"